# Generated by Django 2.2.12 on 2020-04-13 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la iniciativa', max_length=128, null=True, verbose_name='Nombre')),
                ('summary', models.TextField(help_text='Explícanos la iniciativa para que podamos valorar tu solicitud', null=True, verbose_name='Descripción')),
                ('ip', models.GenericIPAddressField(help_text='IP del servidor donde vas a alojar el dominio', null=True, verbose_name='IP')),
                ('domain', models.CharField(help_text='Escoge el subdominio que deseas usar. Por ejemplo un valor "ejemplo" creará un subdominio "ejemplo.coop.re"', max_length=128, null=True, verbose_name='Subdominio')),
                ('email', models.EmailField(help_text='Un correo electrónico para que podamos contactar contigo', max_length=254, null=True, verbose_name='Correo electrónico')),
                ('slug', models.SlugField(blank=True, verbose_name='Content slug')),
                ('creation_date', models.DateField(default=django.utils.timezone.now, editable=False, verbose_name='Creation date')),
                ('update_date', models.DateField(auto_now=True, verbose_name='Last modified')),
                ('published', models.BooleanField(default=False, verbose_name='Publico')),
            ],
            options={
                'verbose_name_plural': 'iniciativas',
                'verbose_name': 'iniciativa',
            },
        ),
    ]
