# Generated by Django 2.0.2 on 2020-04-12 13:13

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextBlock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Escoge el nombre que se verá públicamente asociado a este perfil', max_length=128, null=True, verbose_name='Nombre')),
                ('body', ckeditor_uploader.fields.RichTextUploadingField(help_text='Texto del bloque', null=True, verbose_name='Texto')),
            ],
            options={
                'verbose_name_plural': 'bloques',
                'verbose_name': 'bloque',
            },
        ),
    ]
